name: CI
on: [push, pull_request]
jobs:
  Verification:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux",
            os: ubuntu-latest
          }
        - {
            name: "Windows",
            os: windows-latest
          }
    steps:
      - name: Create the Projects directory
        run: mkdir Projects
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: Projects/${{ github.event.repository.name }}
      - name: Resolve the dependencies
        run: |
          cd Projects/${{ github.event.repository.name }}
          ./run.sh deps
      - name: Set up the project
        run: |
          cd Projects/${{ github.event.repository.name }}
          ./run.sh setup
      - name: Test the commit message checker
        if: runner.os == 'Linux'
        run: |
          cd Projects/${{ github.event.repository.name }}/tools/git/hooks
          ./test_commit-msg
      - name: Check the commit message
        # on pull_request, available commit message is not found by the tried command
        if: runner.os == 'Linux' && github.event_name != 'pull_request'
        run: |
          cd Projects/${{ github.event.repository.name }}/tools/git/hooks
          git log -1 --pretty=%B > ./commitMessage
          ./commit-msg ./commitMessage
          rm ./commitMessage
      - name: Build
        run: |
          cd Projects/${{ github.event.repository.name }}
          ./run.sh config
          ./run.sh build
      - name: Run the application and the tests
        run: |
          cd Projects/${{ github.event.repository.name }}
          ./run.sh run
          ./run.sh test
          cd ./build && ctest && cd -
      - name: Run Valgrind
        if: runner.os == 'Linux'
        run: |
          cd Projects/${{ github.event.repository.name }}
          sudo apt install valgrind
          ./run.sh setDeb
          ./run.sh config
          ./run.sh build
          ./run.sh valgrind
          ./run.sh setRel
      - name: Test coverage
        if: runner.os == 'Linux'
        run: |
          cd Projects/${{ github.event.repository.name }}
          sudo apt install lcov
          ./run.sh testCov
      - name: Analyse the code
        run: |
          cd Projects/${{ github.event.repository.name }}
          ./run.sh analyseCode
