name: CppSampleProject CI
on: [push, pull_request]
jobs:
  CppSampleProject:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux",
            os: ubuntu-latest
          }
        - {
            name: "Windows",
            os: windows-latest
          }
    steps:
      - name: Resolve the dependencies
        run: |
          mkdir Deps
          cd Deps
          git clone https://github.com/google/googletest.git         
          if ("${{ runner.os }}" STREQUAL "Linux")
            cmake -S googletest -B googletest/build
          elseif ("${{ runner.os }}" STREQUAL "Windows")
            cmake -S googletest -B googletest/build -G "MinGW Makefiles"
          endif()
          cmake --build googletest/build
          cd ..
      - name: Create the Projects directory
        run: mkdir Projects
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: Projects/CppSampleProject
      - name: Set up the project
        run: |
          cd Projects/CppSampleProject
          if ("${{ runner.os }}" STREQUAL "Linux")
            ./setup.sh
          elseif ("${{ runner.os }}" STREQUAL "Windows")
            ./setup.bat
          endif()
      - name: Build
        run: |
          cd Projects/CppSampleProject
          if ("${{ runner.os }}" STREQUAL "Linux")
            cmake -B build -G
          elseif ("${{ runner.os }}" STREQUAL "Windows")
            cmake -B build -G "MinGW Makefiles"
          endif()
          cd build
          cmake --build .
      - name: Run the application and the tests
        run: |
          cd Projects/CppSampleProject/build
          src/CppSampleProject
          test/CppSampleProjectTest
          ctest
